FROM busybox:latest
ENV PORT=8000
LABEL maintainer="Luhmann <mluhmann@phoenixcontact.com>"

ADD index.html index.html

EXPOSE $PORT

COPY start.sh start.sh
RUN chmod -v +x start.sh

HEALTHCHECK CMD nc -z localhost $PORT
CMD ["./start.sh"]