// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IDeviceInfoService.proto

#include "IDeviceInfoService.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_ArpTypes_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ObjectType_ArpTypes_2eproto;
namespace Arp {
namespace Device {
namespace Interface {
namespace Services {
namespace Grpc {
class IDeviceInfoServiceGetItemRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<IDeviceInfoServiceGetItemRequest> _instance;
} _IDeviceInfoServiceGetItemRequest_default_instance_;
class IDeviceInfoServiceGetItemsRequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<IDeviceInfoServiceGetItemsRequest> _instance;
} _IDeviceInfoServiceGetItemsRequest_default_instance_;
class IDeviceInfoServiceGetItemResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<IDeviceInfoServiceGetItemResponse> _instance;
} _IDeviceInfoServiceGetItemResponse_default_instance_;
class IDeviceInfoServiceGetItemsResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<IDeviceInfoServiceGetItemsResponse> _instance;
} _IDeviceInfoServiceGetItemsResponse_default_instance_;
}  // namespace Grpc
}  // namespace Services
}  // namespace Interface
}  // namespace Device
}  // namespace Arp
static void InitDefaultsscc_info_IDeviceInfoServiceGetItemRequest_IDeviceInfoService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Arp::Device::Interface::Services::Grpc::_IDeviceInfoServiceGetItemRequest_default_instance_;
    new (ptr) ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_IDeviceInfoServiceGetItemRequest_IDeviceInfoService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_IDeviceInfoServiceGetItemRequest_IDeviceInfoService_2eproto}, {}};

static void InitDefaultsscc_info_IDeviceInfoServiceGetItemResponse_IDeviceInfoService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Arp::Device::Interface::Services::Grpc::_IDeviceInfoServiceGetItemResponse_default_instance_;
    new (ptr) ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_IDeviceInfoServiceGetItemResponse_IDeviceInfoService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_IDeviceInfoServiceGetItemResponse_IDeviceInfoService_2eproto}, {
      &scc_info_ObjectType_ArpTypes_2eproto.base,}};

static void InitDefaultsscc_info_IDeviceInfoServiceGetItemsRequest_IDeviceInfoService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Arp::Device::Interface::Services::Grpc::_IDeviceInfoServiceGetItemsRequest_default_instance_;
    new (ptr) ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemsRequest();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_IDeviceInfoServiceGetItemsRequest_IDeviceInfoService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_IDeviceInfoServiceGetItemsRequest_IDeviceInfoService_2eproto}, {}};

static void InitDefaultsscc_info_IDeviceInfoServiceGetItemsResponse_IDeviceInfoService_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Arp::Device::Interface::Services::Grpc::_IDeviceInfoServiceGetItemsResponse_default_instance_;
    new (ptr) ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemsResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_IDeviceInfoServiceGetItemsResponse_IDeviceInfoService_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_IDeviceInfoServiceGetItemsResponse_IDeviceInfoService_2eproto}, {
      &scc_info_ObjectType_ArpTypes_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_IDeviceInfoService_2eproto[4];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_IDeviceInfoService_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_IDeviceInfoService_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_IDeviceInfoService_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemRequest, identifier_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemsRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemsRequest, identifiers_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemResponse, _returnvalue_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemsResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemsResponse, _returnvalue_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemRequest)},
  { 6, -1, sizeof(::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemsRequest)},
  { 12, -1, sizeof(::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemResponse)},
  { 18, -1, sizeof(::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemsResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Arp::Device::Interface::Services::Grpc::_IDeviceInfoServiceGetItemRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Arp::Device::Interface::Services::Grpc::_IDeviceInfoServiceGetItemsRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Arp::Device::Interface::Services::Grpc::_IDeviceInfoServiceGetItemResponse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Arp::Device::Interface::Services::Grpc::_IDeviceInfoServiceGetItemsResponse_default_instance_),
};

const char descriptor_table_protodef_IDeviceInfoService_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030IDeviceInfoService.proto\022\"Arp.Device.I"
  "nterface.Services.Grpc\032\016ArpTypes.proto\"6"
  "\n IDeviceInfoServiceGetItemRequest\022\022\n\nid"
  "entifier\030\001 \001(\t\"8\n!IDeviceInfoServiceGetI"
  "temsRequest\022\023\n\013identifiers\030\001 \003(\t\"T\n!IDev"
  "iceInfoServiceGetItemResponse\022/\n\014_Return"
  "Value\030\001 \001(\0132\031.Arp.Type.Grpc.ObjectType\"U"
  "\n\"IDeviceInfoServiceGetItemsResponse\022/\n\014"
  "_ReturnValue\030\001 \003(\0132\031.Arp.Type.Grpc.Objec"
  "tType2\315\002\n\022IDeviceInfoService\022\230\001\n\007GetItem"
  "\022D.Arp.Device.Interface.Services.Grpc.ID"
  "eviceInfoServiceGetItemRequest\032E.Arp.Dev"
  "ice.Interface.Services.Grpc.IDeviceInfoS"
  "erviceGetItemResponse\"\000\022\233\001\n\010GetItems\022E.A"
  "rp.Device.Interface.Services.Grpc.IDevic"
  "eInfoServiceGetItemsRequest\032F.Arp.Device"
  ".Interface.Services.Grpc.IDeviceInfoServ"
  "iceGetItemsResponse\"\000b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_IDeviceInfoService_2eproto_deps[1] = {
  &::descriptor_table_ArpTypes_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_IDeviceInfoService_2eproto_sccs[4] = {
  &scc_info_IDeviceInfoServiceGetItemRequest_IDeviceInfoService_2eproto.base,
  &scc_info_IDeviceInfoServiceGetItemResponse_IDeviceInfoService_2eproto.base,
  &scc_info_IDeviceInfoServiceGetItemsRequest_IDeviceInfoService_2eproto.base,
  &scc_info_IDeviceInfoServiceGetItemsResponse_IDeviceInfoService_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_IDeviceInfoService_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_IDeviceInfoService_2eproto = {
  false, false, descriptor_table_protodef_IDeviceInfoService_2eproto, "IDeviceInfoService.proto", 709,
  &descriptor_table_IDeviceInfoService_2eproto_once, descriptor_table_IDeviceInfoService_2eproto_sccs, descriptor_table_IDeviceInfoService_2eproto_deps, 4, 1,
  schemas, file_default_instances, TableStruct_IDeviceInfoService_2eproto::offsets,
  file_level_metadata_IDeviceInfoService_2eproto, 4, file_level_enum_descriptors_IDeviceInfoService_2eproto, file_level_service_descriptors_IDeviceInfoService_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_IDeviceInfoService_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_IDeviceInfoService_2eproto)), true);
namespace Arp {
namespace Device {
namespace Interface {
namespace Services {
namespace Grpc {

// ===================================================================

class IDeviceInfoServiceGetItemRequest::_Internal {
 public:
};

IDeviceInfoServiceGetItemRequest::IDeviceInfoServiceGetItemRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemRequest)
}
IDeviceInfoServiceGetItemRequest::IDeviceInfoServiceGetItemRequest(const IDeviceInfoServiceGetItemRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  identifier_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_identifier().empty()) {
    identifier_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_identifier(), 
      GetArena());
  }
  // @@protoc_insertion_point(copy_constructor:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemRequest)
}

void IDeviceInfoServiceGetItemRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_IDeviceInfoServiceGetItemRequest_IDeviceInfoService_2eproto.base);
  identifier_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

IDeviceInfoServiceGetItemRequest::~IDeviceInfoServiceGetItemRequest() {
  // @@protoc_insertion_point(destructor:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void IDeviceInfoServiceGetItemRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  identifier_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void IDeviceInfoServiceGetItemRequest::ArenaDtor(void* object) {
  IDeviceInfoServiceGetItemRequest* _this = reinterpret_cast< IDeviceInfoServiceGetItemRequest* >(object);
  (void)_this;
}
void IDeviceInfoServiceGetItemRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void IDeviceInfoServiceGetItemRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const IDeviceInfoServiceGetItemRequest& IDeviceInfoServiceGetItemRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_IDeviceInfoServiceGetItemRequest_IDeviceInfoService_2eproto.base);
  return *internal_default_instance();
}


void IDeviceInfoServiceGetItemRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  identifier_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IDeviceInfoServiceGetItemRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string identifier = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_identifier();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemRequest.identifier"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* IDeviceInfoServiceGetItemRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string identifier = 1;
  if (this->identifier().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_identifier().data(), static_cast<int>(this->_internal_identifier().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemRequest.identifier");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_identifier(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemRequest)
  return target;
}

size_t IDeviceInfoServiceGetItemRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string identifier = 1;
  if (this->identifier().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_identifier());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void IDeviceInfoServiceGetItemRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const IDeviceInfoServiceGetItemRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<IDeviceInfoServiceGetItemRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemRequest)
    MergeFrom(*source);
  }
}

void IDeviceInfoServiceGetItemRequest::MergeFrom(const IDeviceInfoServiceGetItemRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.identifier().size() > 0) {
    _internal_set_identifier(from._internal_identifier());
  }
}

void IDeviceInfoServiceGetItemRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void IDeviceInfoServiceGetItemRequest::CopyFrom(const IDeviceInfoServiceGetItemRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IDeviceInfoServiceGetItemRequest::IsInitialized() const {
  return true;
}

void IDeviceInfoServiceGetItemRequest::InternalSwap(IDeviceInfoServiceGetItemRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  identifier_.Swap(&other->identifier_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}

::PROTOBUF_NAMESPACE_ID::Metadata IDeviceInfoServiceGetItemRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class IDeviceInfoServiceGetItemsRequest::_Internal {
 public:
};

IDeviceInfoServiceGetItemsRequest::IDeviceInfoServiceGetItemsRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  identifiers_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsRequest)
}
IDeviceInfoServiceGetItemsRequest::IDeviceInfoServiceGetItemsRequest(const IDeviceInfoServiceGetItemsRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      identifiers_(from.identifiers_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsRequest)
}

void IDeviceInfoServiceGetItemsRequest::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_IDeviceInfoServiceGetItemsRequest_IDeviceInfoService_2eproto.base);
}

IDeviceInfoServiceGetItemsRequest::~IDeviceInfoServiceGetItemsRequest() {
  // @@protoc_insertion_point(destructor:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void IDeviceInfoServiceGetItemsRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void IDeviceInfoServiceGetItemsRequest::ArenaDtor(void* object) {
  IDeviceInfoServiceGetItemsRequest* _this = reinterpret_cast< IDeviceInfoServiceGetItemsRequest* >(object);
  (void)_this;
}
void IDeviceInfoServiceGetItemsRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void IDeviceInfoServiceGetItemsRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const IDeviceInfoServiceGetItemsRequest& IDeviceInfoServiceGetItemsRequest::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_IDeviceInfoServiceGetItemsRequest_IDeviceInfoService_2eproto.base);
  return *internal_default_instance();
}


void IDeviceInfoServiceGetItemsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  identifiers_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IDeviceInfoServiceGetItemsRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated string identifiers = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_identifiers();
            ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsRequest.identifiers"));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* IDeviceInfoServiceGetItemsRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string identifiers = 1;
  for (int i = 0, n = this->_internal_identifiers_size(); i < n; i++) {
    const auto& s = this->_internal_identifiers(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsRequest.identifiers");
    target = stream->WriteString(1, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsRequest)
  return target;
}

size_t IDeviceInfoServiceGetItemsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string identifiers = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(identifiers_.size());
  for (int i = 0, n = identifiers_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      identifiers_.Get(i));
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void IDeviceInfoServiceGetItemsRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const IDeviceInfoServiceGetItemsRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<IDeviceInfoServiceGetItemsRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsRequest)
    MergeFrom(*source);
  }
}

void IDeviceInfoServiceGetItemsRequest::MergeFrom(const IDeviceInfoServiceGetItemsRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  identifiers_.MergeFrom(from.identifiers_);
}

void IDeviceInfoServiceGetItemsRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void IDeviceInfoServiceGetItemsRequest::CopyFrom(const IDeviceInfoServiceGetItemsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IDeviceInfoServiceGetItemsRequest::IsInitialized() const {
  return true;
}

void IDeviceInfoServiceGetItemsRequest::InternalSwap(IDeviceInfoServiceGetItemsRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  identifiers_.InternalSwap(&other->identifiers_);
}

::PROTOBUF_NAMESPACE_ID::Metadata IDeviceInfoServiceGetItemsRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class IDeviceInfoServiceGetItemResponse::_Internal {
 public:
  static const ::Arp::Type::Grpc::ObjectType& _returnvalue(const IDeviceInfoServiceGetItemResponse* msg);
};

const ::Arp::Type::Grpc::ObjectType&
IDeviceInfoServiceGetItemResponse::_Internal::_returnvalue(const IDeviceInfoServiceGetItemResponse* msg) {
  return *msg->_returnvalue_;
}
void IDeviceInfoServiceGetItemResponse::clear__returnvalue() {
  if (GetArena() == nullptr && _returnvalue_ != nullptr) {
    delete _returnvalue_;
  }
  _returnvalue_ = nullptr;
}
IDeviceInfoServiceGetItemResponse::IDeviceInfoServiceGetItemResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemResponse)
}
IDeviceInfoServiceGetItemResponse::IDeviceInfoServiceGetItemResponse(const IDeviceInfoServiceGetItemResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has__returnvalue()) {
    _returnvalue_ = new ::Arp::Type::Grpc::ObjectType(*from._returnvalue_);
  } else {
    _returnvalue_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemResponse)
}

void IDeviceInfoServiceGetItemResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_IDeviceInfoServiceGetItemResponse_IDeviceInfoService_2eproto.base);
  _returnvalue_ = nullptr;
}

IDeviceInfoServiceGetItemResponse::~IDeviceInfoServiceGetItemResponse() {
  // @@protoc_insertion_point(destructor:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void IDeviceInfoServiceGetItemResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete _returnvalue_;
}

void IDeviceInfoServiceGetItemResponse::ArenaDtor(void* object) {
  IDeviceInfoServiceGetItemResponse* _this = reinterpret_cast< IDeviceInfoServiceGetItemResponse* >(object);
  (void)_this;
}
void IDeviceInfoServiceGetItemResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void IDeviceInfoServiceGetItemResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const IDeviceInfoServiceGetItemResponse& IDeviceInfoServiceGetItemResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_IDeviceInfoServiceGetItemResponse_IDeviceInfoService_2eproto.base);
  return *internal_default_instance();
}


void IDeviceInfoServiceGetItemResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && _returnvalue_ != nullptr) {
    delete _returnvalue_;
  }
  _returnvalue_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IDeviceInfoServiceGetItemResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .Arp.Type.Grpc.ObjectType _ReturnValue = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable__returnvalue(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* IDeviceInfoServiceGetItemResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Arp.Type.Grpc.ObjectType _ReturnValue = 1;
  if (this->has__returnvalue()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::_returnvalue(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemResponse)
  return target;
}

size_t IDeviceInfoServiceGetItemResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .Arp.Type.Grpc.ObjectType _ReturnValue = 1;
  if (this->has__returnvalue()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_returnvalue_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void IDeviceInfoServiceGetItemResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const IDeviceInfoServiceGetItemResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<IDeviceInfoServiceGetItemResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemResponse)
    MergeFrom(*source);
  }
}

void IDeviceInfoServiceGetItemResponse::MergeFrom(const IDeviceInfoServiceGetItemResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has__returnvalue()) {
    _internal_mutable__returnvalue()->::Arp::Type::Grpc::ObjectType::MergeFrom(from._internal__returnvalue());
  }
}

void IDeviceInfoServiceGetItemResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void IDeviceInfoServiceGetItemResponse::CopyFrom(const IDeviceInfoServiceGetItemResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IDeviceInfoServiceGetItemResponse::IsInitialized() const {
  return true;
}

void IDeviceInfoServiceGetItemResponse::InternalSwap(IDeviceInfoServiceGetItemResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_returnvalue_, other->_returnvalue_);
}

::PROTOBUF_NAMESPACE_ID::Metadata IDeviceInfoServiceGetItemResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class IDeviceInfoServiceGetItemsResponse::_Internal {
 public:
};

void IDeviceInfoServiceGetItemsResponse::clear__returnvalue() {
  _returnvalue_.Clear();
}
IDeviceInfoServiceGetItemsResponse::IDeviceInfoServiceGetItemsResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  _returnvalue_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsResponse)
}
IDeviceInfoServiceGetItemsResponse::IDeviceInfoServiceGetItemsResponse(const IDeviceInfoServiceGetItemsResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _returnvalue_(from._returnvalue_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsResponse)
}

void IDeviceInfoServiceGetItemsResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_IDeviceInfoServiceGetItemsResponse_IDeviceInfoService_2eproto.base);
}

IDeviceInfoServiceGetItemsResponse::~IDeviceInfoServiceGetItemsResponse() {
  // @@protoc_insertion_point(destructor:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void IDeviceInfoServiceGetItemsResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void IDeviceInfoServiceGetItemsResponse::ArenaDtor(void* object) {
  IDeviceInfoServiceGetItemsResponse* _this = reinterpret_cast< IDeviceInfoServiceGetItemsResponse* >(object);
  (void)_this;
}
void IDeviceInfoServiceGetItemsResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void IDeviceInfoServiceGetItemsResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const IDeviceInfoServiceGetItemsResponse& IDeviceInfoServiceGetItemsResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_IDeviceInfoServiceGetItemsResponse_IDeviceInfoService_2eproto.base);
  return *internal_default_instance();
}


void IDeviceInfoServiceGetItemsResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _returnvalue_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IDeviceInfoServiceGetItemsResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated .Arp.Type.Grpc.ObjectType _ReturnValue = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add__returnvalue(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* IDeviceInfoServiceGetItemsResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Arp.Type.Grpc.ObjectType _ReturnValue = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal__returnvalue_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal__returnvalue(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsResponse)
  return target;
}

size_t IDeviceInfoServiceGetItemsResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Arp.Type.Grpc.ObjectType _ReturnValue = 1;
  total_size += 1UL * this->_internal__returnvalue_size();
  for (const auto& msg : this->_returnvalue_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void IDeviceInfoServiceGetItemsResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const IDeviceInfoServiceGetItemsResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<IDeviceInfoServiceGetItemsResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsResponse)
    MergeFrom(*source);
  }
}

void IDeviceInfoServiceGetItemsResponse::MergeFrom(const IDeviceInfoServiceGetItemsResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  _returnvalue_.MergeFrom(from._returnvalue_);
}

void IDeviceInfoServiceGetItemsResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void IDeviceInfoServiceGetItemsResponse::CopyFrom(const IDeviceInfoServiceGetItemsResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Arp.Device.Interface.Services.Grpc.IDeviceInfoServiceGetItemsResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IDeviceInfoServiceGetItemsResponse::IsInitialized() const {
  return true;
}

void IDeviceInfoServiceGetItemsResponse::InternalSwap(IDeviceInfoServiceGetItemsResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  _returnvalue_.InternalSwap(&other->_returnvalue_);
}

::PROTOBUF_NAMESPACE_ID::Metadata IDeviceInfoServiceGetItemsResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Grpc
}  // namespace Services
}  // namespace Interface
}  // namespace Device
}  // namespace Arp
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemRequest* Arena::CreateMaybeMessage< ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemsRequest* Arena::CreateMaybeMessage< ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemsRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemsRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemResponse* Arena::CreateMaybeMessage< ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemsResponse* Arena::CreateMaybeMessage< ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemsResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Arp::Device::Interface::Services::Grpc::IDeviceInfoServiceGetItemsResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
