// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: IDeviceStatusService.proto

#include "IDeviceStatusService.pb.h"
#include "IDeviceStatusService.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Arp {
namespace Device {
namespace Interface {
namespace Services {
namespace Grpc {

static const char* IDeviceStatusService_method_names[] = {
  "/Arp.Device.Interface.Services.Grpc.IDeviceStatusService/GetItem",
  "/Arp.Device.Interface.Services.Grpc.IDeviceStatusService/GetItems",
};

std::unique_ptr< IDeviceStatusService::Stub> IDeviceStatusService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< IDeviceStatusService::Stub> stub(new IDeviceStatusService::Stub(channel));
  return stub;
}

IDeviceStatusService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetItem_(IDeviceStatusService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetItems_(IDeviceStatusService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status IDeviceStatusService::Stub::GetItem(::grpc::ClientContext* context, const ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemRequest& request, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemRequest, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetItem_, context, request, response);
}

void IDeviceStatusService::Stub::experimental_async::GetItem(::grpc::ClientContext* context, const ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemRequest* request, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemRequest, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetItem_, context, request, response, std::move(f));
}

void IDeviceStatusService::Stub::experimental_async::GetItem(::grpc::ClientContext* context, const ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemRequest* request, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetItem_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemResponse>* IDeviceStatusService::Stub::PrepareAsyncGetItemRaw(::grpc::ClientContext* context, const ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemResponse, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetItem_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemResponse>* IDeviceStatusService::Stub::AsyncGetItemRaw(::grpc::ClientContext* context, const ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetItemRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status IDeviceStatusService::Stub::GetItems(::grpc::ClientContext* context, const ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsRequest& request, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsRequest, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetItems_, context, request, response);
}

void IDeviceStatusService::Stub::experimental_async::GetItems(::grpc::ClientContext* context, const ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsRequest* request, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsRequest, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetItems_, context, request, response, std::move(f));
}

void IDeviceStatusService::Stub::experimental_async::GetItems(::grpc::ClientContext* context, const ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsRequest* request, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetItems_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsResponse>* IDeviceStatusService::Stub::PrepareAsyncGetItemsRaw(::grpc::ClientContext* context, const ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsResponse, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetItems_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsResponse>* IDeviceStatusService::Stub::AsyncGetItemsRaw(::grpc::ClientContext* context, const ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetItemsRaw(context, request, cq);
  result->StartCall();
  return result;
}

IDeviceStatusService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      IDeviceStatusService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< IDeviceStatusService::Service, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemRequest, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](IDeviceStatusService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemRequest* req,
             ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemResponse* resp) {
               return service->GetItem(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      IDeviceStatusService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< IDeviceStatusService::Service, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsRequest, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](IDeviceStatusService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsRequest* req,
             ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsResponse* resp) {
               return service->GetItems(ctx, req, resp);
             }, this)));
}

IDeviceStatusService::Service::~Service() {
}

::grpc::Status IDeviceStatusService::Service::GetItem(::grpc::ServerContext* context, const ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemRequest* request, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status IDeviceStatusService::Service::GetItems(::grpc::ServerContext* context, const ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsRequest* request, ::Arp::Device::Interface::Services::Grpc::IDeviceStatusServiceGetItemsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Arp
}  // namespace Device
}  // namespace Interface
}  // namespace Services
}  // namespace Grpc

