// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileSystemEntry.proto

#include "FileSystemEntry.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace Arp {
namespace System {
namespace Commons {
namespace Services {
namespace Io {
namespace Grpc {
class FileSystemEntryDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<FileSystemEntry> _instance;
} _FileSystemEntry_default_instance_;
}  // namespace Grpc
}  // namespace Io
}  // namespace Services
}  // namespace Commons
}  // namespace System
}  // namespace Arp
static void InitDefaultsscc_info_FileSystemEntry_FileSystemEntry_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Arp::System::Commons::Services::Io::Grpc::_FileSystemEntry_default_instance_;
    new (ptr) ::Arp::System::Commons::Services::Io::Grpc::FileSystemEntry();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_FileSystemEntry_FileSystemEntry_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_FileSystemEntry_FileSystemEntry_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_FileSystemEntry_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_FileSystemEntry_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_FileSystemEntry_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_FileSystemEntry_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Arp::System::Commons::Services::Io::Grpc::FileSystemEntry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Arp::System::Commons::Services::Io::Grpc::FileSystemEntry, path_),
  PROTOBUF_FIELD_OFFSET(::Arp::System::Commons::Services::Io::Grpc::FileSystemEntry, isfile_),
  PROTOBUF_FIELD_OFFSET(::Arp::System::Commons::Services::Io::Grpc::FileSystemEntry, isdirectory_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Arp::System::Commons::Services::Io::Grpc::FileSystemEntry)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Arp::System::Commons::Services::Io::Grpc::_FileSystemEntry_default_instance_),
};

const char descriptor_table_protodef_FileSystemEntry_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025FileSystemEntry.proto\022#Arp.System.Comm"
  "ons.Services.Io.Grpc\"D\n\017FileSystemEntry\022"
  "\014\n\004Path\030\001 \001(\t\022\016\n\006IsFile\030\002 \001(\010\022\023\n\013IsDirec"
  "tory\030\003 \001(\010b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_FileSystemEntry_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_FileSystemEntry_2eproto_sccs[1] = {
  &scc_info_FileSystemEntry_FileSystemEntry_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_FileSystemEntry_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_FileSystemEntry_2eproto = {
  false, false, descriptor_table_protodef_FileSystemEntry_2eproto, "FileSystemEntry.proto", 138,
  &descriptor_table_FileSystemEntry_2eproto_once, descriptor_table_FileSystemEntry_2eproto_sccs, descriptor_table_FileSystemEntry_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_FileSystemEntry_2eproto::offsets,
  file_level_metadata_FileSystemEntry_2eproto, 1, file_level_enum_descriptors_FileSystemEntry_2eproto, file_level_service_descriptors_FileSystemEntry_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_FileSystemEntry_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_FileSystemEntry_2eproto)), true);
namespace Arp {
namespace System {
namespace Commons {
namespace Services {
namespace Io {
namespace Grpc {

// ===================================================================

class FileSystemEntry::_Internal {
 public:
};

FileSystemEntry::FileSystemEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Arp.System.Commons.Services.Io.Grpc.FileSystemEntry)
}
FileSystemEntry::FileSystemEntry(const FileSystemEntry& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_path().empty()) {
    path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_path(), 
      GetArena());
  }
  ::memcpy(&isfile_, &from.isfile_,
    static_cast<size_t>(reinterpret_cast<char*>(&isdirectory_) -
    reinterpret_cast<char*>(&isfile_)) + sizeof(isdirectory_));
  // @@protoc_insertion_point(copy_constructor:Arp.System.Commons.Services.Io.Grpc.FileSystemEntry)
}

void FileSystemEntry::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_FileSystemEntry_FileSystemEntry_2eproto.base);
  path_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&isfile_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&isdirectory_) -
      reinterpret_cast<char*>(&isfile_)) + sizeof(isdirectory_));
}

FileSystemEntry::~FileSystemEntry() {
  // @@protoc_insertion_point(destructor:Arp.System.Commons.Services.Io.Grpc.FileSystemEntry)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void FileSystemEntry::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  path_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void FileSystemEntry::ArenaDtor(void* object) {
  FileSystemEntry* _this = reinterpret_cast< FileSystemEntry* >(object);
  (void)_this;
}
void FileSystemEntry::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void FileSystemEntry::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const FileSystemEntry& FileSystemEntry::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_FileSystemEntry_FileSystemEntry_2eproto.base);
  return *internal_default_instance();
}


void FileSystemEntry::Clear() {
// @@protoc_insertion_point(message_clear_start:Arp.System.Commons.Services.Io.Grpc.FileSystemEntry)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  path_.ClearToEmpty();
  ::memset(&isfile_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&isdirectory_) -
      reinterpret_cast<char*>(&isfile_)) + sizeof(isdirectory_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* FileSystemEntry::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string Path = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_path();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Arp.System.Commons.Services.Io.Grpc.FileSystemEntry.Path"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool IsFile = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          isfile_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool IsDirectory = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          isdirectory_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* FileSystemEntry::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Arp.System.Commons.Services.Io.Grpc.FileSystemEntry)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string Path = 1;
  if (this->path().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_path().data(), static_cast<int>(this->_internal_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Arp.System.Commons.Services.Io.Grpc.FileSystemEntry.Path");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_path(), target);
  }

  // bool IsFile = 2;
  if (this->isfile() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_isfile(), target);
  }

  // bool IsDirectory = 3;
  if (this->isdirectory() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_isdirectory(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Arp.System.Commons.Services.Io.Grpc.FileSystemEntry)
  return target;
}

size_t FileSystemEntry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Arp.System.Commons.Services.Io.Grpc.FileSystemEntry)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string Path = 1;
  if (this->path().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_path());
  }

  // bool IsFile = 2;
  if (this->isfile() != 0) {
    total_size += 1 + 1;
  }

  // bool IsDirectory = 3;
  if (this->isdirectory() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FileSystemEntry::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Arp.System.Commons.Services.Io.Grpc.FileSystemEntry)
  GOOGLE_DCHECK_NE(&from, this);
  const FileSystemEntry* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<FileSystemEntry>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Arp.System.Commons.Services.Io.Grpc.FileSystemEntry)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Arp.System.Commons.Services.Io.Grpc.FileSystemEntry)
    MergeFrom(*source);
  }
}

void FileSystemEntry::MergeFrom(const FileSystemEntry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Arp.System.Commons.Services.Io.Grpc.FileSystemEntry)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.path().size() > 0) {
    _internal_set_path(from._internal_path());
  }
  if (from.isfile() != 0) {
    _internal_set_isfile(from._internal_isfile());
  }
  if (from.isdirectory() != 0) {
    _internal_set_isdirectory(from._internal_isdirectory());
  }
}

void FileSystemEntry::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Arp.System.Commons.Services.Io.Grpc.FileSystemEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FileSystemEntry::CopyFrom(const FileSystemEntry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Arp.System.Commons.Services.Io.Grpc.FileSystemEntry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FileSystemEntry::IsInitialized() const {
  return true;
}

void FileSystemEntry::InternalSwap(FileSystemEntry* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  path_.Swap(&other->path_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileSystemEntry, isdirectory_)
      + sizeof(FileSystemEntry::isdirectory_)
      - PROTOBUF_FIELD_OFFSET(FileSystemEntry, isfile_)>(
          reinterpret_cast<char*>(&isfile_),
          reinterpret_cast<char*>(&other->isfile_));
}

::PROTOBUF_NAMESPACE_ID::Metadata FileSystemEntry::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Grpc
}  // namespace Io
}  // namespace Services
}  // namespace Commons
}  // namespace System
}  // namespace Arp
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Arp::System::Commons::Services::Io::Grpc::FileSystemEntry* Arena::CreateMaybeMessage< ::Arp::System::Commons::Services::Io::Grpc::FileSystemEntry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Arp::System::Commons::Services::Io::Grpc::FileSystemEntry >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
