// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SessionState.proto

#include "SessionState.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace Arp {
namespace Services {
namespace DataLogger {
namespace Services {
namespace Grpc {
}  // namespace Grpc
}  // namespace Services
}  // namespace DataLogger
}  // namespace Services
}  // namespace Arp
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_SessionState_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_SessionState_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_SessionState_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_SessionState_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_SessionState_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022SessionState.proto\022%Arp.Services.DataL"
  "ogger.Services.Grpc*m\n\014SessionState\022\013\n\007S"
  "S_None\020\000\022\016\n\nSS_Created\020\001\022\022\n\016SS_Initializ"
  "ed\020\002\022\016\n\nSS_Running\020\003\022\016\n\nSS_Stopped\020\004\022\014\n\010"
  "SS_Error\020\005b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_SessionState_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_SessionState_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_SessionState_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_SessionState_2eproto = {
  false, false, descriptor_table_protodef_SessionState_2eproto, "SessionState.proto", 178,
  &descriptor_table_SessionState_2eproto_once, descriptor_table_SessionState_2eproto_sccs, descriptor_table_SessionState_2eproto_deps, 0, 0,
  schemas, file_default_instances, TableStruct_SessionState_2eproto::offsets,
  file_level_metadata_SessionState_2eproto, 0, file_level_enum_descriptors_SessionState_2eproto, file_level_service_descriptors_SessionState_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_SessionState_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_SessionState_2eproto)), true);
namespace Arp {
namespace Services {
namespace DataLogger {
namespace Services {
namespace Grpc {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SessionState_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_SessionState_2eproto);
  return file_level_enum_descriptors_SessionState_2eproto[0];
}
bool SessionState_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Grpc
}  // namespace Services
}  // namespace DataLogger
}  // namespace Services
}  // namespace Arp
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
