services:
  rosbridge:
# add _${APP_UNIQUE_NAME} to all of your container_name
    container_name: rosbridge_${APP_UNIQUE_NAME}
# Use the Image ID or fully qualified path incl. sha256 to avoid conflicts
    image: ${image:-§§IMAGE_ID§§}
    stdin_open: true # podman run -i
    tty: true        # podman run -t
    volumes:
      - /run/plcnext/grpc.sock:/run/plcnext/grpc.sock
    restart: unless-stopped
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
    command: bash -c "ros2 launch phoenix_bridge launch_phoenix_bridge.py"