#ifndef INCLUDE_TYPES_H
#define INCLUDE_TYPES_H

#include <rclcpp/rclcpp.hpp>

/**
 * @brief This header contains the common types that are to be used throughout the bridge. 
 * Specifically the ros message headers, which are generated based on the parameters file
 */

///
/// The following section is generated by cog at build time. Manual edits will be lost when rebuilt.
///

/*[[[cog
import cog
import sys
import os

sys.path.append(os.getcwd()) # Necessary when colcon build invokes this script

from phoenix_bridge.param_parser import ParamParser, getResolvedTypeName

parser = ParamParser()
for node in parser.nodes_:
      cog.outl("#include<{}.hpp>".format(node.header_name))
]]]*/
#include<nav_msgs/msg/odometry.hpp>
#include<geometry_msgs/msg/twist.hpp>
#include<std_msgs/msg/string.hpp>
//[[[end]]]

///
/// The above section is generated by cog at build time. Manual edits will be lost when rebuilt.
///

#endif // INCLUDE_TYPES_H
