//
// Copyright 2022 Fraunhofer IPA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#ifndef INCLUDE_TYPES_H
#define INCLUDE_TYPES_H

#include <rclcpp/rclcpp.hpp>

/**
 * @brief This header contains the common types that are to be used throughout the bridge. 
 * Specifically the ros message headers, which are generated based on the parameters file
 */

///
/// The following section is generated by cog at build time. Manual edits will be lost when rebuilt.
///

/*[[[cog
import cog
import sys
import os

sys.path.append(os.getcwd()) # Necessary when colcon build invokes this script

from phoenix_bridge.param_parser import ParamParser, getSnakeCase

parser = ParamParser()
for node in parser.nodes_:
      cog.outl("#include<{}.hpp>".format(getSnakeCase(node.msg_type)))
]]]*/
#include<nav_msgs/msg/odometry.hpp>
#include<geometry_msgs/msg/twist.hpp>
#include<std_msgs/msg/string.hpp>
//[[[end]]]

///
/// The above section is generated by cog at build time. Manual edits will be lost when rebuilt.
///

#endif // INCLUDE_TYPES_H
